language: ruby
bundler_args: --without development
rvm:
  - 2.1.2
env:
  global:
    - RAILS_ENV=test
    - JS_DRIVER=phantomjs
branches:
  only:
    - master
script: 'rake suite'
notifications:
  recipients:
    - kaethorn@gmail.com
